#include "GPIO_def.h"

const uint32_t bit_position_val_tbl[32] ={
    GPIO_PIN_0,                        
    GPIO_PIN_1,                        
    GPIO_PIN_2,                        
    GPIO_PIN_3,                       
    GPIO_PIN_4,                      
    GPIO_PIN_5,                     
    GPIO_PIN_6,                    
    GPIO_PIN_7,                   
    GPIO_PIN_8,                  
    GPIO_PIN_9,                 
    GPIO_PIN_10,               
    GPIO_PIN_11,              
    GPIO_PIN_12,             
    GPIO_PIN_13,            
    GPIO_PIN_14,           
    GPIO_PIN_15,          
    GPIO_PIN_16,         
    GPIO_PIN_17,        
    GPIO_PIN_19,       
    GPIO_PIN_20,      
    GPIO_PIN_21,     
    GPIO_PIN_22,    
    GPIO_PIN_23,   
    GPIO_PIN_24,  
    GPIO_PIN_25,  
    GPIO_PIN_26,                     
    GPIO_PIN_27,                    
    GPIO_PIN_28,                   
    GPIO_PIN_29,                  
    GPIO_PIN_30,                 
    GPIO_PIN_31,                
    GPIO_PIN_32,               
};

/*GPIO Port index*/
