#include "GPIO_def.h"

const uint32_t bit_position_val_tbl[32] ={
    GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7,
    GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15,
    GPIO_BSRR_BR0,GPIO_BSRR_BR1,GPIO_BSRR_BR2,GPIO_BSRR_BR3,GPIO_BSRR_BR4,GPIO_BSRR_BR5,GPIO_BSRR_BR6,
    GPIO_BSRR_BR7,GPIO_BSRR_BR8,GPIO_BSRR_BR9,GPIO_BSRR_BR10,GPIO_BSRR_BR11,GPIO_BSRR_BR12,GPIO_BSRR_BR13,
    GPIO_BSRR_BR14,GPIO_BSRR_BR15
};

/*GPIO Port index*/
